
name: Demo GitHub Actions Workflow

on:
  push:
    branches:
      - main

# Grant permission to dispatch other workflows
permissions:
  contents: read              # to check out your code
  actions: write              # to trigger workflow_dispatch
  pull-requests: write        # if you ever comment on PRs

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: sleep 2

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Test
        run: sleep 2

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Deploy
        run: sleep 2

  run_observepoint_audits:
    name: Run ObservePoint Audits
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Start ObservePoint audits
        uses: ./.github/actions/run_op_audit
        with:
          audit_ids: '230171'
          starting_urls: 'https://dominos.ua/uk/kyiv,https://dominos.ua/'
          op_api_key: ${{ secrets.OP_API_KEY }}
          callback_owner: ${{ github.repository_owner }}
          callback_repo: ${{ github.event.repository.name }}
          callback_workflow_file: 'audit-complete.yml'
          callback_ref: 'main'
          pr_number: ${{ github.event.pull_request.number }}
          commit_sha: ${{ github.sha }}
